post:
  tags:
  - Roles
  summary: Creates a new role.
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/CreateRoleDto.yaml
      text/json:
        schema:
          $ref: ../../components/schemas/CreateRoleDto.yaml
      application/*+json:
        schema:
          $ref: ../../components/schemas/CreateRoleDto.yaml
  responses:
    '201':
      description: Role created successfully
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/RoleModel.yaml
    '400':
      description: Invalid role data
    '409':
      description: Role with this name already exists
