get:
  tags:
  - Roles
  summary: Retrieves a role by its name.
  parameters:
  - name: roleName
    in: path
    required: true
    schema:
      type: string
  responses:
    '200':
      description: Role found
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/RoleModel.yaml
    '400':
      description: Invalid name input
    '404':
      description: Role not found
delete:
  tags:
  - Roles
  summary: Deletes a role by name.
  parameters:
  - name: roleName
    in: path
    required: true
    schema:
      type: string
  responses:
    '200':
      description: Deleted successfully
    '403':
      description: Forbidden to delete this role
    '404':
      description: Role not found
    '409':
      description: Cannot delete role (e.g., users assigned)
