get:
  tags:
  - Roles
  summary: Checks if a role exists.
  parameters:
  - name: checkBy
    in: query
    schema:
      type: string
  - name: value
    in: query
    schema:
      type: string
  responses:
    '200':
      description: Check completed
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/RoleExistsResponseDto.yaml
    '400':
      description: Invalid search parameters
