get:
  tags:
  - Roles
  summary: Gets all permissions assigned to a role.
  parameters:
  - name: roleId
    in: path
    required: true
    schema:
      type: integer
      format: int64
  responses:
    '200':
      description: Permissions retrieved
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../../components/schemas/RolePermissionModel.yaml
    '404':
      description: Role or permissions not found
post:
  tags:
  - Roles
  summary: Assigns a permission to a role.
  parameters:
  - name: roleId
    in: path
    required: true
    schema:
      type: integer
      format: int64
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/AddPermissionToRoleDto.yaml
      text/json:
        schema:
          $ref: ../../components/schemas/AddPermissionToRoleDto.yaml
      application/*+json:
        schema:
          $ref: ../../components/schemas/AddPermissionToRoleDto.yaml
  responses:
    '200':
      description: Permission assigned
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/RolePermissionModel.yaml
    '404':
      description: Role or permission not found
    '409':
      description: Permission already assigned
