openapi: 3.0.4
info: {}
paths:
  /api/Business:
    $ref: ./paths/Business/api_Business.yaml
  /api/Business/{id}:
    $ref: ./paths/Business/api_Business__id_.yaml
  /api/Business/all:
    $ref: ./paths/Business/api_Business_all.yaml
  /api/Business/{address}:
    $ref: ./paths/Business/api_Business__address_.yaml
  /api/BusinessParking:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking.yaml
  /api/BusinessParking/self:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking_self.yaml
  /api/BusinessParking/{id}:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking__id_.yaml
  /api/BusinessParking/business/{id}:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking_business__id_.yaml
  /api/BusinessParking/{licensePlate}:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking__licensePlate_.yaml
  /api/BusinessParking/active/{licensePlate}:
    $ref: ./paths/BusinessParkingRegistrations/api_BusinessParking_active__licensePlate_.yaml
  /api/HotelPasses:
    $ref: ./paths/HotelPasses/api_HotelPasses.yaml
  /api/HotelPasses/self:
    $ref: ./paths/HotelPasses/api_HotelPasses_self.yaml
  /api/HotelPasses/{id}:
    $ref: ./paths/HotelPasses/api_HotelPasses__id_.yaml
  /api/HotelPasses/parkinglot/{id}:
    $ref: ./paths/HotelPasses/api_HotelPasses_parkinglot__id_.yaml
  /api/HotelPasses/license-plate:
    $ref: ./paths/HotelPasses/api_HotelPasses_license-plate.yaml
  /api/HotelPasses/{parkingLotId}/license-plate:
    $ref: ./paths/HotelPasses/api_HotelPasses__parkingLotId__license-plate.yaml
  /api/HotelPasses/admin/{id}:
    $ref: ./paths/HotelPasses/api_HotelPasses_admin__id_.yaml
  /api/HotelPasses/self/{id}:
    $ref: ./paths/HotelPasses/api_HotelPasses_self__id_.yaml
  /api/Hotels:
    $ref: ./paths/Hotels/api_Hotels.yaml
  /api/Hotels/{id}:
    $ref: ./paths/Hotels/api_Hotels__id_.yaml
  /api/LicensePlate:
    $ref: ./paths/LicensePlate/api_LicensePlate.yaml
  /api/LicensePlate/{licensePlate}/entry:
    $ref: ./paths/LicensePlate/api_LicensePlate__licensePlate__entry.yaml
  /api/LicensePlate/{licensePlate}:
    $ref: ./paths/LicensePlate/api_LicensePlate__licensePlate_.yaml
  /api/ParkingLots:
    $ref: ./paths/ParkingLots/api_ParkingLots.yaml
  /api/ParkingLots/{lotId}:
    $ref: ./paths/ParkingLots/api_ParkingLots__lotId_.yaml
  /api/ParkingLots/by-address:
    $ref: ./paths/ParkingLots/api_ParkingLots_by-address.yaml
  /api/ParkingLots/by-id/{lotId}:
    $ref: ./paths/ParkingLots/api_ParkingLots_by-id__lotId_.yaml
  /api/ParkingLots/by-address/{address}:
    $ref: ./paths/ParkingLots/api_ParkingLots_by-address__address_.yaml
  /api/ParkingLots/all:
    $ref: ./paths/ParkingLots/api_ParkingLots_all.yaml
  /api/ParkingSession/{lotId}/sessions/start:
    $ref: ./paths/ParkingSession/api_ParkingSession__lotId__sessions_start.yaml
  /api/ParkingSession/{lotId}/sessions/stop:
    $ref: ./paths/ParkingSession/api_ParkingSession__lotId__sessions_stop.yaml
  /api/ParkingSession/{lotId}/sessions/{sessionId}:
    $ref: ./paths/ParkingSession/api_ParkingSession__lotId__sessions__sessionId_.yaml
  /api/ParkingSession/{lotId}/sessions:
    $ref: ./paths/ParkingSession/api_ParkingSession__lotId__sessions.yaml
  /api/Payments:
    $ref: ./paths/Payments/api_Payments.yaml
  /api/Payments/refund:
    $ref: ./paths/Payments/api_Payments_refund.yaml
  /api/Payments/{paymentId}:
    $ref: ./paths/Payments/api_Payments__paymentId_.yaml
  /api/Payments/{username}:
    $ref: ./paths/Payments/api_Payments__username_.yaml
  /api/Payments/id/{paymentId}:
    $ref: ./paths/Payments/api_Payments_id__paymentId_.yaml
  /api/Payments/transaction/{transactionId}:
    $ref: ./paths/Payments/api_Payments_transaction__transactionId_.yaml
  /api/Payments/plate/{licensePlate}:
    $ref: ./paths/Payments/api_Payments_plate__licensePlate_.yaml
  /api/Reservations:
    $ref: ./paths/Reservations/api_Reservations.yaml
  /api/Reservations/{reservationId}:
    $ref: ./paths/Reservations/api_Reservations__reservationId_.yaml
  /api/Reservations/estimate:
    $ref: ./paths/Reservations/api_Reservations_estimate.yaml
  /api/Roles:
    $ref: ./paths/Roles/api_Roles.yaml
  /api/Roles/{roleId}:
    $ref: ./paths/Roles/api_Roles__roleId_.yaml
  /api/Roles/name/{roleName}:
    $ref: ./paths/Roles/api_Roles_name__roleName_.yaml
  /api/Roles/exists:
    $ref: ./paths/Roles/api_Roles_exists.yaml
  /api/Roles/{roleId}/permissions:
    $ref: ./paths/Roles/api_Roles__roleId__permissions.yaml
  /api/Roles/{roleId}/permissions/{permissionId}:
    $ref: ./paths/Roles/api_Roles__roleId__permissions__permissionId_.yaml
  /api/Users/register:
    $ref: ./paths/Users/api_Users_register.yaml
  /api/Users/login:
    $ref: ./paths/Users/api_Users_login.yaml
  /api/Users/profile:
    $ref: ./paths/Users/api_Users_profile.yaml
  /api/Users/{id}:
    $ref: ./paths/Users/api_Users__id_.yaml
  /api/Users/admin/users/{id}:
    $ref: ./paths/Users/api_Users_admin_users__id_.yaml
  /api/Users/admin/users/{id}/identity:
    $ref: ./paths/Users/api_Users_admin_users__id__identity.yaml
  /api/Users/admin/users/{id}/role:
    $ref: ./paths/Users/api_Users_admin_users__id__role.yaml
  /api/Users/admin/users:
    $ref: ./paths/Users/api_Users_admin_users.yaml
  /api/Users/logout:
    $ref: ./paths/Users/api_Users_logout.yaml
components:
  schemas:
    AddPermissionToRoleDto:
      $ref: ./components/schemas/AddPermissionToRoleDto.yaml
    AdminCreateHotelPassDto:
      $ref: ./components/schemas/AdminCreateHotelPassDto.yaml
    AdminUserProfileDto:
      $ref: ./components/schemas/AdminUserProfileDto.yaml
    AuthDto:
      $ref: ./components/schemas/AuthDto.yaml
    BusinessModel:
      $ref: ./components/schemas/BusinessModel.yaml
    BusinessParkingRegistrationModel:
      $ref: ./components/schemas/BusinessParkingRegistrationModel.yaml
    CreateBusinessDto:
      $ref: ./components/schemas/CreateBusinessDto.yaml
    CreateBusinessRegAdminDto:
      $ref: ./components/schemas/CreateBusinessRegAdminDto.yaml
    CreateBusinessRegDto:
      $ref: ./components/schemas/CreateBusinessRegDto.yaml
    CreateHotelDto:
      $ref: ./components/schemas/CreateHotelDto.yaml
    CreateHotelPassDto:
      $ref: ./components/schemas/CreateHotelPassDto.yaml
    CreateLicensePlateDto:
      $ref: ./components/schemas/CreateLicensePlateDto.yaml
    CreateParkingLotDto:
      $ref: ./components/schemas/CreateParkingLotDto.yaml
    CreatePaymentDto:
      $ref: ./components/schemas/CreatePaymentDto.yaml
    CreateReservationDto:
      $ref: ./components/schemas/CreateReservationDto.yaml
    CreateRoleDto:
      $ref: ./components/schemas/CreateRoleDto.yaml
    HotelModel:
      $ref: ./components/schemas/HotelModel.yaml
    HotelPassModel:
      $ref: ./components/schemas/HotelPassModel.yaml
    LicensePlateModel:
      $ref: ./components/schemas/LicensePlateModel.yaml
    LoginDto:
      $ref: ./components/schemas/LoginDto.yaml
    ParkingLotModel:
      $ref: ./components/schemas/ParkingLotModel.yaml
    ParkingLotStatus:
      $ref: ./components/schemas/ParkingLotStatus.yaml
    ParkingSessionModel:
      $ref: ./components/schemas/ParkingSessionModel.yaml
    ParkingSessionStatus:
      $ref: ./components/schemas/ParkingSessionStatus.yaml
    PatchBusinessDto:
      $ref: ./components/schemas/PatchBusinessDto.yaml
    PatchBusinessRegDto:
      $ref: ./components/schemas/PatchBusinessRegDto.yaml
    PatchHotelDto:
      $ref: ./components/schemas/PatchHotelDto.yaml
    PatchHotelPassDto:
      $ref: ./components/schemas/PatchHotelPassDto.yaml
    PatchParkingLotDto:
      $ref: ./components/schemas/PatchParkingLotDto.yaml
    PaymentModel:
      $ref: ./components/schemas/PaymentModel.yaml
    PaymentRefundDto:
      $ref: ./components/schemas/PaymentRefundDto.yaml
    PaymentResponseDto:
      $ref: ./components/schemas/PaymentResponseDto.yaml
    PermissionModel:
      $ref: ./components/schemas/PermissionModel.yaml
    ReadBusinessDto:
      $ref: ./components/schemas/ReadBusinessDto.yaml
    ReadBusinessRegDto:
      $ref: ./components/schemas/ReadBusinessRegDto.yaml
    ReadHotelDto:
      $ref: ./components/schemas/ReadHotelDto.yaml
    ReadHotelPassDto:
      $ref: ./components/schemas/ReadHotelPassDto.yaml
    ReadLicensePlateDto:
      $ref: ./components/schemas/ReadLicensePlateDto.yaml
    ReadParkingLotDto:
      $ref: ./components/schemas/ReadParkingLotDto.yaml
    RefundResponseDto:
      $ref: ./components/schemas/RefundResponseDto.yaml
    RegisterDto:
      $ref: ./components/schemas/RegisterDto.yaml
    ReservationCostEstimateRequest:
      $ref: ./components/schemas/ReservationCostEstimateRequest.yaml
    ReservationCostEstimateResponseDto:
      $ref: ./components/schemas/ReservationCostEstimateResponseDto.yaml
    ReservationModel:
      $ref: ./components/schemas/ReservationModel.yaml
    ReservationResponseDto:
      $ref: ./components/schemas/ReservationResponseDto.yaml
    ReservationStatus:
      $ref: ./components/schemas/ReservationStatus.yaml
    RoleExistsResponseDto:
      $ref: ./components/schemas/RoleExistsResponseDto.yaml
    RoleModel:
      $ref: ./components/schemas/RoleModel.yaml
    RolePermissionModel:
      $ref: ./components/schemas/RolePermissionModel.yaml
    SessionInvoiceDto:
      $ref: ./components/schemas/SessionInvoiceDto.yaml
    StartParkingSessionDto:
      $ref: ./components/schemas/StartParkingSessionDto.yaml
    StartSessionResponseDto:
      $ref: ./components/schemas/StartSessionResponseDto.yaml
    StopParkingSessionDto:
      $ref: ./components/schemas/StopParkingSessionDto.yaml
    StopSessionResponseDto:
      $ref: ./components/schemas/StopSessionResponseDto.yaml
    TransactionDataDto:
      $ref: ./components/schemas/TransactionDataDto.yaml
    TransactionModel:
      $ref: ./components/schemas/TransactionModel.yaml
    UpdateLicensePlateRequest:
      $ref: ./components/schemas/UpdateLicensePlateRequest.yaml
    UpdateReservationDto:
      $ref: ./components/schemas/UpdateReservationDto.yaml
    UpdateRoleDto:
      $ref: ./components/schemas/UpdateRoleDto.yaml
    UpdateUserDto:
      $ref: ./components/schemas/UpdateUserDto.yaml
    UpdateUserIdentityDto:
      $ref: ./components/schemas/UpdateUserIdentityDto.yaml
    UpdateUserRoleDto:
      $ref: ./components/schemas/UpdateUserRoleDto.yaml
    UserModel:
      $ref: ./components/schemas/UserModel.yaml
    UserProfileDto:
      $ref: ./components/schemas/UserProfileDto.yaml
  securitySchemes:
    Bearer:
      type: http
      description: 'Please enter a valid token (e.g., ''Bearer eyJ...'').

        You can obtain a token by logging in or registering a new account via the
        endpoints.'
      scheme: Bearer
      bearerFormat: JWT
security:
- Bearer: []
